name: Foxy Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  foxy_build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ros:foxy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install SMTP dependencies
        run: |
          apt-get update
          apt-get install -y libz3-dev
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          vcs-repo-file-url: ${GITHUB_WORKSPACE}/dependencies.repos
          target-ros2-distro: foxy
          coverage-result: false
          skip-tests: true
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
